### ISSUE TITLE
PKHeX.Android fails to build after cleaning

### ISSUE THREAD

**Issue by kpalian** [kwsch/PKHeX.Mobile#13]
The Android app is impossible to compile because it does not build in VS2019.

**Comment by kwsch** [comment]
Builds fine in VS2019. You need to install the mobile development packages (Xamarin) via the Visual Studio Installer.

https://docs.microsoft.com/en-us/xamarin/get-started/installation/

**Comment by kpalian** [comment]
I have the Xamarin packages installed, I just get an error when rebuilding solution after cleaning all.

**Comment by kpalian** [comment]
![Here's the log, in case that helps](https://user-images.githubusercontent.com/29902286/89350050-1c69f080-d664-11ea-8be6-26c40adddd25.png)

**Comment by kwsch** [comment]
Might be that the AutoLegality dll needs to be manually updated to match the latest PKHeX.Core logic, as there's some unused methods present which mono is having trouble correlating. Weird, didn't happen on my end when I updated and tested on a new emulator-phone...
