### ISSUE TITLE
No release

### ISSUE THREAD

**Issue by BestPancake69** [kwsch/PKHeX.Mobile#18]
The application advertised does not have a release. No options to download compatible application files (IPA, APK, EXE, etc.) exist. Please review your work and take it down if no release will be available or rename your project to correct the false advertising.

**Comment by architdate** [comment]
😂😂😂😂😂😂😂😂😂😂

**Comment by x79-sys** [comment]
code it your self than lmfao don't harrass the devs

**Comment by BestPancake69** [comment]
> code it your self than lmfao don't harrass the devs

No form of harassment is present. Thank you for your time. It is simply a correction on the title of their work because it is misleading. Also. If there is no release, they did no develop anything. It's simply there as a tease. Cheers

**Comment by kwsch** [comment]
It works; build it yourself.

**Comment by architdate** [comment]
> If there is no release, they did no(t) develop anything. It's simply there as a tease

If the issue poster can't build, they simply don't deserve anything. The issue is there simply as a meme

**Comment by BestPancake69** [comment]
> It works; build it yourself.

The files provided are not compatible on iOS. I cannot directly and accurately state that android does or does not support these files. However, the files are not supported on iOS and iPhones cannot build code. So stating that these work is simply a lie or a misunderstanding. These files are 𝙣𝙤𝙩 compatible for iOS and cannot be used. 

Please review the title of your work and make corrections where corrections are needed. Cheers

**Comment by architdate** [comment]
Compile the IPA and then test. You don't just throw the source code on iphone and expect it to work. Setup a xamarin build environment and then build the IPA
