### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by fefo-dev** [kwsch/PKHeX.Mobile#2]
Hello.

I was unable to build an apk after setting up my computer with the latest Visual Studio and Android Studio, about a month ago. Probably a mistake of my part, but it wasn't anything I could solve at my skill level. Can someone help me, or provide a working build?

I'll try it again and put the results here later.

Thanks

**Comment by fefo-dev** [comment]
Tried to reproduce my errors, with my phone connect by chance, and it all went well. Wasn't aware of that, sorry. The apk works, i.e. does nothing, so there's that.

**Comment by aecarvalho** [comment]
> Tried to reproduce my errors, with my phone connect by chance, and it all went well. Wasn't aware of that, sorry. The apk works, i.e. does nothing, so there's that.

But by any chance did you create a working build?

**Comment by fefo-dev** [comment]
Yes I did. There is a basic interface in place, but no functionality.

**Comment by aecarvalho** [comment]
> Yes I did. There is a basic interface in place, but no functionality.

So it can't edit a 3DS "main" save file? Could you please send me the apk on my email acajcarvalho@gmail.com if possible? Would be much appreciated, thanks in advance

**Comment by fefo-dev** [comment]
There's zero funcionality whatsoever, but be my guest since I got a backup. Uploaded here, to expire tomorrow if @kwsch isn't about it: https://easyupload.io/jow7f1

**Comment by aecarvalho** [comment]
Thanks so much, I definitely would have built on my own if I had a PC, my friend uses Android Suite, not Xamarin Forms project so he couldn't help either
