### ISSUE TITLE
faild open to directory

### ISSUE THREAD

**Issue by dmakm** [kwsch/PKHeX.Mobile#21]
Creating C:\Users\운터공룡\AppData\Local\Xamarin.Android\Cache\Mono.Android.Platform.ApiLevel_28.apk
Creating C:\Users\운터공룡\AppData\Local\Xamarin.Android\Cache\Mono.Android.Platform.ApiLevel_28.apk
Copying platform assemblies...
Copying platform assemblies...
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v4.4\Mono.Android.Export.dll
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v4.4\OpenTK-1.0.dll
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v4.4\Mono.Android.Export.pdb
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v4.4\OpenTK-1.0.pdb
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\mono.android.dex
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.dll
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\mono.android.jar
Copying file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\common7\ide\ReferenceAssemblies\Microsoft\Framework\MonoAndroid\v9.0\Mono.Android.pdb
Copying platform assemblies...
Creating: C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\AndroidManifest.xml
Creating: C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\unaligned.apk
Executing: C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\aapt.exe package -f -0 .dll -0 .mdb -M "C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\AndroidManifest.xml" -I "C:\Program Files (x86)\Android\android-sdk\platforms\android-30\android.jar" -F "C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\unaligned.apk" -k "C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\r"
Aapt
C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\aapt.exe exited with value: 0
Aapt
Creating: C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\unsigned.apk
Executing: C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\zipalign.exe 4 "C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\unaligned.apk" "C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\unsigned.apk"
zipalign
C:\Program Files (x86)\Android\android-sdk\build-tools\29.0.2\zipalign.exe exited with value: 0
zipalign
Creating: C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd\Mono.Android.Platform.ApiLevel_28.apk
1>------ Build started: Project: PKHeX.Android, Configuration: Debug Any CPU ------
Removing temporary directory: C:\Users\운터공룡\AppData\Local\Temp\lea5p1ef.exd
Creating C:\Users\운터공룡\AppData\Local\Xamarin.Android\Cache\Mono.Android.Platform.ApiLevel_28.apk
1>C:\Users\운터공룡\Downloads\PKHeX.Mobile-master\PKHeX.Mobile-master\PKHeX.Android\obj\Debug\90\lp\39\jl\res : error APT2097: failed to open directory: 지정된 파일을 찾을 수 없습니다. (2).
1>C:\Users\운터공룡\Downloads\PKHeX.Mobile-master\PKHeX.Mobile-master\PKHeX.Android\obj\Debug\90\lp\32\jl\res : error APT2097: failed to open directory: 지정된 파일을 찾을 수 없습니다. (2).
========== Build: 0 succeeded, 1 failed, 2 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by kwsch** [comment]
General build failures are not an issue with PKHeX.Mobile.
