### ISSUE TITLE
Can't build PKHex with Visual Studio for Mac

### ISSUE THREAD

**Issue by jkashuba07** [kwsch/PKHeX.Mobile#25]
Hi,

Every time I try to build PKHex.IOS I always get 5 errors and I am not sure why. I made sure all my Nuget packages were up to date after downloading a fresh copy of the code. After that I clean the solution and then rebuild solution.

I get this all the time.

<img width="2017" alt="Screen Shot 2021-01-20 at 11 43 07 AM" src="https://user-images.githubusercontent.com/32431242/105206812-c7883c80-5b14-11eb-82e7-3a769a164c69.png">

Just a disclaimer. I am a complete noob. I really don't much of anything passed, clean, rebuild, deploy

**Comment by jkashuba07** [comment]
Maybe this is a better screenshot

![image](https://user-images.githubusercontent.com/32431242/105209002-54cc9080-5b17-11eb-928c-a6cf64b0a611.png)

**Comment by kwsch** [comment]
The NuGet package reference should be an older version of PKHeX.Core, as recent changes to the PKHeX library have changed some property names and method locations.

If you really wanted the latest core, you'd have to update the above errors to point to the correct location.

MysteryGift Format is now Generation, AltForm is now Form, and FormConverter is now FormInfo

**Comment by jkashuba07** [comment]
Thank you for the explanation. Is there detail on replacing it with the core that I have now? I assume the core needed is in the code somewhere that I downloaded?

**Comment by kwsch** [comment]
The `csproj` states which nuget package it wants.

https://github.com/kwsch/PKHeX.Mobile/blob/b0a74ca21c7f9435222ca3c55158a98e91a2ec5d/PKHeX.Drawing/PKHeX.Drawing.csproj#L6946

**Comment by jkashuba07** [comment]
Thank you very much for the help. I started fresh and verified the core and all. When I do the process now, I get this at the build stage. I am not sure if it means anything, as it seems to have just built it anyways.

![image](https://user-images.githubusercontent.com/32431242/105356182-14c1e800-5bc1-11eb-9694-5edc2aad97e3.png)

**Comment by kwsch** [comment]
The program compiles fine without alterations; if you change one project's package requirements, you should change then all.

**Comment by jkashuba07** [comment]
@kwsch Just wanted to thank you. You are right, I attempted on my PC, everything goes as planned. For some reason starting fresh on the mac just comes back with warnings or errors. I'll stick to PC

I truly appreciate everything you do!
