### ISSUE TITLE
Can't change Pokemon gender

### ISSUE THREAD

**Issue by MrPurple666** [kwsch/PKHeX.Mobile#28]
It's impossible to change the pokemon's genre (It automatically chooses male as gender), so legendary pokemons like kyogre stick with this "cheat mark"

**Comment by kwsch** [comment]
The GUI is limited in what is implemented. Nobody has submitted pull requests to extend what is currently available, and I have my other tools/repos that I prefer to give my attention to. 

You can try using the Legalize functionality to have it auto-fix stuff after species/form changes, and edit the result of that.

**Comment by MrPurple666** [comment]
I understand.

Fixed using QrCode with the necessary properties (Shiny also works)
