### ISSUE TITLE
It's impossible to build a working apk

### ISSUE THREAD

**Issue by FerdinandoPH** [kwsch/PKHeX.Mobile#31]
I have been trying to build the app for two hours, and, after having to learn what Xamarin is (because there is no release), every apk I have generated won't install (my phone displays a message saying that "the application was not installed", which is very frustrating, since it worked fine with debugging. Since I couldn't build the app by following the instructions on the readme I have been researching what could be wrong, but nothing I have tried has worked. Could you please tell me what is wrong? Or give me the apk? I really want to use the app, but I've thrown in the towel at this point

**Comment by FerdinandoPH** [comment]
If you need any output, feel free to ask me

**Comment by kwsch** [comment]
https://social.msdn.microsoft.com/Forums/en-US/76813b96-cc7e-42f0-8a42-15b817e47917/why-the-aplication-didnt-install?forum=xamarinforms

**Comment by FerdinandoPH** [comment]
I tried that, it says that "the app is uninstalled for this user" and I can't uninstall it, even after rebooting.
![Screenshot_20210808-221500](https://user-images.githubusercontent.com/29411787/128644573-e63d8406-e7b5-4ca5-a29d-a49ed13fc605.jpg)

**Comment by kwsch** [comment]
I've set up a public CI pipeline that posts builds of the apk.

1. Click the green checkmark of a commit, view more details on azure
2. Related -> 1 published
3. click the `...` dropdown at the far right, and download.

**Comment by FerdinandoPH** [comment]
![Captura de pantalla (31)](https://user-images.githubusercontent.com/29411787/129199816-a645e7d7-1263-4622-a77b-c8ff61193881.png)
I tried to download the apk (from the artifact you can see in the photo) and yet I still get a message saying that the application was not  installed. I have a Oneplus 6T with Android 10, what might be the problem?
![WhatsApp Image 2021-08-12 at 14 54 01](https://user-images.githubusercontent.com/29411787/129200158-7d421986-7269-4789-8ba8-fcd18f27a203.jpeg)

**Comment by kwsch** [comment]
It's likely an issue with the phone; you'll likely have to troubleshoot the error messages yourself as this isn't really an issue with this project.

https://www.preguntandroid.com/pregunta/17216/aplicacion-no-instalada-para-este-usuario

**Comment by cactysman** [comment]
I got a Pixel 2XL on Android 11 and all three of the available APKs fail to install without further notice, as it does for OP.

I'm not familiar with Android apps written in C#, but I'll try to have a look at the repository to maybe figure out what's wrong.
