### ISSUE TITLE
Coud someone help me? 

### ISSUE THREAD

**Issue by Diegor96** [kwsch/PKHeX.Mobile#38]
![Screenshot_20211111_014942_com ProjectPokemon PKHeX](https://user-images.githubusercontent.com/94101318/141251493-a6479478-5408-45a3-b1c2-080f9f142842.jpg)
I don't know why this happens, says "This file is being passed as a URI instead of path" someone help me please

**Comment by kwsch** [comment]
Are you using the latest build?

**Comment by DGgreat1507** [comment]
> Are you using the latest build?

I am getting the same error and using the latest build if this error is only coming in this build xan you pls send the link for working one.

**Comment by Diegor96** [comment]
> > Are you using the latest build?
> 
> I am getting the same error and using the latest build if this error is only coming in this build xan you pls send the link for working one.

I found a solution that worked to me. I am using a phone huawei with android 9
![Screenshot_20211111_094123_com brave browser](https://user-images.githubusercontent.com/94101318/141320881-a4849b35-ff5c-40c2-95be-db8863586f24.jpg)

**Comment by Diegor96** [comment]
> > > Are you using the latest build?
> > 
> > 
> > I am getting the same error and using the latest build if this error is only coming in this build xan you pls send the link for working one.
> 
> I found a solution that worked to me. I am using a phone huawei with android 9 ![Screenshot_20211111_094123_com brave browser](https://user-images.githubusercontent.com/94101318/141320881-a4849b35-ff5c-40c2-95be-db8863586f24.jpg) ![Screenshot_20211111_095031_com estrongs android pop](https://user-images.githubusercontent.com/94101318/141321151-f3524a34-370d-4bb6-9fb9-6b96f0875b20.jpg) ![Screenshot_20211111_095024_com estrongs android pop](https://user-images.githubusercontent.com/94101318/141321156-a1be8be6-6faf-4b0c-8a7e-01c2ec1a58ef.jpg) ![Screenshot_20211111_095017_com estrongs android pop](https://user-images.githubusercontent.com/94101318/141321160-79efb020-6adf-447d-867a-d3e566506a1e.jpg)

I hope that helps you
