### ISSUE TITLE
Buenas vieras que el pkhex Mobile no me quiere abrir la partida guardada ahora como voy a crear mis Pokémon que hago

### ISSUE THREAD

**Issue by Isaac22Mora** [kwsch/PKHeX.Mobile#44]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kwsch** [comment]
Invalid issue body; you need to be descriptive.

**Comment by Isaac22Mora** [comment]
Hello, i'll tell You that Pkhex Mobile doesn't want to cache the save file now, how am i going to create my Pokémon it says that file is denied, what do I do?

**Comment by Atrius97** [comment]
PKHeX Mobile last updated on October 8th 2021. It won't load savefiles from any games that have released since then, like Brilliant Diamond/Shining Pearl, or Legends Arceus.

You'll either have to wait for an update, use PKHeX for windows, or update it yourself.

**Comment by Isaac22Mora** [comment]
How do I update PKHeX Mobile, and also I don't have a computer

**Comment by kwsch** [comment]
Download the latest build and install it, same way you installed it the first time.

**Comment by Isaac22Mora** [comment]
How do I do that?

**Comment by Isaac22Mora** [comment]
Could You give me a link because
I'm new to Github

**Comment by Isaac22Mora** [comment]
Is that i install it by Google drive through a link un the description of a video

**Comment by Isaac22Mora** [comment]
Do I have to install it again?
