### ISSUE TITLE
This is the error

### ISSUE THREAD

**Issue by Isaac22Mora** [kwsch/PKHeX.Mobile#45]
![Screenshot_2022-02-09-21-46-02-700_com.ProjectPokemon.PKHeX.jpg](https://user-images.githubusercontent.com/99103359/153333352-beeb14d8-0507-4248-9d3b-7f58105b3d6d.jpg)

**Comment by Isaac22Mora** [comment]
What do you think i'm doing wrong?

**Comment by kwsch** [comment]
1. Don't use old versions from sketchy youtube videos and open issues without testing the latest version available for download.
2. Copy the save file to another path manually.

**Comment by Isaac22Mora** [comment]
I already uninstalled it now how do I download it on Github and how do I update it i am new at this

**Comment by Isaac22Mora** [comment]
Hello again, could you help me please? I need to download PKHeX Mobile on Github, tell me how I do it? please
