### ISSUE TITLE
The pokemon i made appear as if they were traded

### ISSUE THREAD

**Issue by Rainbowlight-pixel** [kwsch/PKHeX.Mobile#46]
Sorry if this is a known issue and has been asked so many times but the pokemon that you make appear as if they were traded, is that just how things work or is it not? Because i have issues with pokemon obeying me at certain levels pls help am i doing something wrong or is this how things work
#38 ``

**Comment by kwsch** [comment]
TID/SID/OT Name/Gender matter.
Edit an existing thing.

**Comment by Rainbowlight-pixel** [comment]
I see thank you for helping have a great day
