### ISSUE TITLE
Not to seem off topic but I'm new to this and I was wondering where I could find more in depth instructions for downloading the iPhone version

### ISSUE THREAD

**Issue by Scrimmag** [kwsch/PKHeX.Mobile#57]
I was also wondering if there would be an easier way to figure out what to download specifically and how? Sorry if this is annoying

**Comment by kwsch** [comment]
There is no "release" or "how to download" besides downloading the green-checkmark build from the pipeline.

There is no iPhone app pre-built, you must build it yourself. Not sure anyone has or will do it for you.
