### ISSUE TITLE
Legalize pokemon

### ISSUE THREAD

**Issue by huzaimbro** [kwsch/PKHeX.Mobile#61]
Legalize pokemon button doesn't work kindly please enable it so I can edit save files in android and I don't have a PC so pls add legalize pokemon function to pkhex.android please 🥺❤️🥺🥺🥺🥺❤️🥺❤️❤️

**Comment by huzaimbro** [comment]
I need it so much

**Comment by kwsch** [comment]
If the current data has moves/etc that is impossible to obtain, then legalizing won't work. Stuff like shiny Celebi in Gen3.

The button is already enabled, doesn't mean it will work for everything you request it to legalize.
