### ISSUE TITLE
Bad checksum detected

### ISSUE THREAD

**Issue by namtambao** [kwsch/PKHeX.Mobile#63]
Whenever i try to load a file (.sav/.dsv) the app tells me: "bad checksum detected" what can i do??

**Comment by kwsch** [comment]
You can press the Continue button to continue, or you can cancel to not load the save file.

                var result = await UserDialogs.Instance.ActionSheetAsync("Bad checksums detected.", "Abort", null, null, proceed).ConfigureAwait(false);

The program tries to ensure your save data is correct.

**Comment by namtambao** [comment]
I'm so sorry, i didn't even notice that "continue" was actually a button, my bad.
