### ISSUE TITLE
doesn't work on android 9

### ISSUE THREAD

**Issue by Luccas7383** [kwsch/PKHeX.Mobile#82]
When I go to install it, it keeps giving this error
![Screenshot_20240216-101811_Package installer](https://github.com/kwsch/PKHeX.Mobile/assets/112060806/f080fc6c-d1d8-4ffa-bafe-6ddb0847590e)

note: I'm Brazilian and that's why it's in Portuguese

**Comment by kwsch** [comment]
Update your phone's Android version. The program needs higher versions.
