### ISSUE TITLE
IVs Displaying error

### ISSUE THREAD

**Issue by iNexusVitto** [kwsch/PKHeX.Mobile#85]
When the IV of a stat is 0 or 31 the stat is not shown. 
Even when a pokemon is "popped" the stat is not present.

**Comment by kwsch** [comment]
"popped"

what?

**Comment by delipunch** [comment]
Doesn't the app use 'pop' to mean load, when selecting a slot? He probably means that.

**Comment by kwsch** [comment]
The text that is displayed as a preview is based on the ShowdownSet markdown, in which 31 IVs and 0 EVs are the "default" values and are not displayed. PKHeX uses this same markdown filtering to remove unnecessary information from view to be able to not overload the user with info.
