### ISSUE TITLE
Rebuild Solution

### ISSUE THREAD

**Issue by Awetspoon** [kwsch/PKHeX.Mobile#87]
![image](https://github.com/kwsch/PKHeX.Mobile/assets/122938825/f996c8eb-8364-474a-9c6a-f9ce8c013aef)
  hey dude was wondering why i get all these warning. saying about the nug package. its all warning but wated to make sure im on the right path. many thanks marcus

**Comment by kwsch** [comment]
Check the output tab. Ignore the warnings if you are not managing the NuGet package updates.

**Comment by Awetspoon** [comment]
ok ignore the package as im not sure how to manage them for this. i rebuilt the whole soltion and this is what i get 

![image](https://github.com/kwsch/PKHeX.Mobile/assets/122938825/5360d067-ce94-485a-9506-d354a4369c41)

![image](https://github.com/kwsch/PKHeX.Mobile/assets/122938825/de8373ee-8f33-4d80-8934-0821028695d2)

**Comment by kwsch** [comment]
If you're manually updating the program yourself, that's up for you to figure out. The current code in this repository works just fine for compiling.

**Comment by Awetspoon** [comment]
Ok awesome thank you. I managed to inject it into my phone from the SLN. I
see in project where you said how to do it. Many thanks dude
